[api]
url = "https://script.google.com/macros/s/AKfycbwrBHdVSwFqs5Zf3rIoY5RDuzIEzRZXWKjiAmnvXOoTmlO7vmPDjX9Q7JTtPyORU3Rz3g/exec"
key = "api_key_spd_generator"

[tte]
email = "ansoriali1980@kemenag.go.id"
password = "Tte-2020"

pemaraf_id = "30703"

penandatangan_1_id = "374"
penandatangan_1_anchors = "^"

penandatangan_2_id = "44"
penandatangan_2_anchors = "$,#,*"